import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["selector", "[data-theme='dark']"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        surface: "var(--surface)",
        "surface-muted": "var(--surface-muted)",
        ink: "var(--ink)",
        body: "var(--body)",
        mute: "var(--mute)",
        hairline: "var(--hairline)",
        "hairline-strong": "var(--hairline-strong)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-ink": "var(--accent-ink)",
        success: "rgb(var(--success) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        console: "var(--console)",
        "console-elevated": "var(--console-elevated)",
        "on-console": "var(--on-console)",
        "on-console-mute": "var(--on-console-mute)",
        "term-bg": "var(--term-bg)",
        "term-bar": "var(--term-bar)",
        "term-border": "var(--term-border)",
        "term-fg": "var(--term-fg)",
        "term-mute": "var(--term-mute)",
        "term-green": "var(--term-green)",
        "term-blue": "var(--term-blue)",
        "term-yellow": "var(--term-yellow)",
        "term-orange": "var(--term-orange)",
        "term-cyan": "var(--term-cyan)",
        "term-elevate": "var(--term-elevate)",
        "term-elevate-strong": "var(--term-elevate-strong)",
        "device-frame": "var(--device-frame)",
        "mac-red": "var(--mac-red)",
        "mac-yellow": "var(--mac-yellow)",
        "mac-green": "var(--mac-green)",
      },
      fontFamily: {
        mono: [
          "var(--font-geist-mono)",
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "PingFang SC",
          "Hiragino Sans GB",
          "Microsoft YaHei",
          "Noto Sans CJK SC",
          "WenQuanYi Micro Hei",
          "sans-serif",
        ],
      },
      borderRadius: {
        sm: "0px",
        md: "0px",
        lg: "0px",
        full: "9999px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
        terminal: "0 18px 50px -12px rgba(0,0,0,0.28)",
        device: "0 24px 60px -20px rgba(0,0,0,0.45)",
      },
      maxWidth: {
        content: "960px",
        frame: "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
